setClass("CallingConv", contains = "EnumValue")

CallingConvValues = structure(c(0L, 8L, 9L, 10L, 11L, 64L, 64L, 65L, 66L, 67L, 68L, 69L, 70L, 71L, 72L, 73L, 74L, 75L, 76L, 77L), .Names = c('C', 'Fast', 'Cold', 'GHC', 'HiPE', 'FirstTargetCC', 'X86_StdCall', 'X86_FastCall', 'ARM_APCS', 'ARM_AAPCS', 'ARM_AAPCS_VFP', 'MSP430_INTR', 'X86_ThisCall', 'PTX_Kernel', 'PTX_Device', 'MBLAZE_INTR', 'MBLAZE_SVOL', 'SPIR_FUNC', 'SPIR_KERNEL', 'Intel_OCL_BI'))

`C` = GenericEnumValue('C', 0L, 'CallingConv')
`Fast` = GenericEnumValue('Fast', 8L, 'CallingConv')
`Cold` = GenericEnumValue('Cold', 9L, 'CallingConv')
`GHC` = GenericEnumValue('GHC', 10L, 'CallingConv')
`HiPE` = GenericEnumValue('HiPE', 11L, 'CallingConv')
`FirstTargetCC` = GenericEnumValue('FirstTargetCC', 64L, 'CallingConv')
`X86_StdCall` = GenericEnumValue('X86_StdCall', 64L, 'CallingConv')
`X86_FastCall` = GenericEnumValue('X86_FastCall', 65L, 'CallingConv')
`ARM_APCS` = GenericEnumValue('ARM_APCS', 66L, 'CallingConv')
`ARM_AAPCS` = GenericEnumValue('ARM_AAPCS', 67L, 'CallingConv')
`ARM_AAPCS_VFP` = GenericEnumValue('ARM_AAPCS_VFP', 68L, 'CallingConv')
`MSP430_INTR` = GenericEnumValue('MSP430_INTR', 69L, 'CallingConv')
`X86_ThisCall` = GenericEnumValue('X86_ThisCall', 70L, 'CallingConv')
`PTX_Kernel` = GenericEnumValue('PTX_Kernel', 71L, 'CallingConv')
`PTX_Device` = GenericEnumValue('PTX_Device', 72L, 'CallingConv')
`MBLAZE_INTR` = GenericEnumValue('MBLAZE_INTR', 73L, 'CallingConv')
`MBLAZE_SVOL` = GenericEnumValue('MBLAZE_SVOL', 74L, 'CallingConv')
`SPIR_FUNC` = GenericEnumValue('SPIR_FUNC', 75L, 'CallingConv')
`SPIR_KERNEL` = GenericEnumValue('SPIR_KERNEL', 76L, 'CallingConv')
`Intel_OCL_BI` = GenericEnumValue('Intel_OCL_BI', 77L, 'CallingConv')

 setAs("character", "CallingConv", function(from) asEnumValue(from, CallingConvValues, "CallingConv", prefix = NA) )
 setAs("integer", "CallingConv", function(from) asEnumValue(from, CallingConvValues, "CallingConv", prefix = NA) )
 setAs("numeric", "CallingConv", function(from) asEnumValue(from, CallingConvValues, "CallingConv", prefix = NA) )
