FCMP_FALSE = 0
FCMP_OEQ = 1
FCMP_OGT = 2
FCMP_OGE = 3
FCMP_OLT = 4
FCMP_OLE = 5
FCMP_ONE = 6
FCMP_ORD = 7
FCMP_UNO = 8
FCMP_UEQ = 9
FCMP_UGT = 10
FCMP_UGE = 11
FCMP_ULT = 12
FCMP_ULE = 13
FCMP_UNE = 14
FCMP_TRUE = 15
FIRST_FCMP_PREDICATE = 0
LAST_FCMP_PREDICATE = 15
BAD_FCMP_PREDICATE = 16
ICMP_EQ = 32
ICMP_NE = 33
ICMP_UGT = 34
ICMP_UGE = 35
ICMP_ULT = 36
ICMP_ULE = 37
ICMP_SGT = 38
ICMP_SGE = 39
ICMP_SLT = 40
ICMP_SLE = 41
FIRST_ICMP_PREDICATE = 32
LAST_ICMP_PREDICATE = 41
BAD_ICMP_PREDICATE = 42


ICmpInst.Predicate = structure(c(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 
12L, 13L, 14L, 15L, 0L, 15L, 16L, 32L, 33L, 34L, 35L, 36L, 37L, 
38L, 39L, 40L, 41L, 32L, 41L, 42L), .Names = c("FCMP_FALSE", 
"FCMP_OEQ", "FCMP_OGT", "FCMP_OGE", "FCMP_OLT", "FCMP_OLE", "FCMP_ONE", 
"FCMP_ORD", "FCMP_UNO", "FCMP_UEQ", "FCMP_UGT", "FCMP_UGE", "FCMP_ULT", 
"FCMP_ULE", "FCMP_UNE", "FCMP_TRUE", "FIRST_FCMP_PREDICATE", 
"LAST_FCMP_PREDICATE", "BAD_FCMP_PREDICATE", "ICMP_EQ", "ICMP_NE", 
"ICMP_UGT", "ICMP_UGE", "ICMP_ULT", "ICMP_ULE", "ICMP_SGT", "ICMP_SGE", 
"ICMP_SLT", "ICMP_SLE", "FIRST_ICMP_PREDICATE", "LAST_ICMP_PREDICATE", 
"BAD_ICMP_PREDICATE"))
