setClass('VectorType', contains = 'Type')
setClass('IntegerType', contains = 'Type')
setClass('FunctionType', contains = 'Type')
setClass('StructType', contains = 'Type')
setClass('ArrayType', contains = 'Type')
setClass('PointerType', contains = 'Type')
setClass('FixedVectorType', contains = 'VectorType')
setClass('ScalableVectorType', contains = 'VectorType')
