setGeneric('isVolatile', function(x, ...)
    standardGeneric('isVolatile'))
setGeneric('isSimple', function(x, ...)
    standardGeneric('isSimple'))
setGeneric('isUnordered', function(x, ...)
    standardGeneric('isUnordered'))
setGeneric('getAlignment', function(x, ...)
    standardGeneric('getAlignment'))
setGeneric('getOrdering', function(x, ...)
    standardGeneric('getOrdering'))
setGeneric('getSyncScopeID', function(x, ...)
    standardGeneric('getSyncScopeID'))
#setGeneric('setAlignment', function(x, align, ...)
#    standardGeneric('setAlignment'))
setGeneric('setOrdering', function(x, ...)
    standardGeneric('setOrdering'))
setGeneric('setSyncScopeID', function(x, ...)
    standardGeneric('setSyncScopeID'))
setGeneric('setVolatile', function(x, ...)
    standardGeneric('setVolatile'))
