setMethod('isVolatile', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_isVolatile', x))
setMethod('isVolatile', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_isVolatile', x))
setMethod('isSimple', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_isSimple', x))
setMethod('isSimple', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_isSimple', x))
setMethod('isUnordered', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_isUnordered', x))
setMethod('isUnordered', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_isUnordered', x))
setMethod('getAlignment', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_getAlignment', x))
setMethod('getAlignment', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_getAlignment', x))
setMethod('getOrdering', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_getOrdering', x))
setMethod('getOrdering', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_getOrdering', x))
setMethod('getSyncScopeID', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_getSyncScopeID', x))
setMethod('getSyncScopeID', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_getSyncScopeID', x))
#setMethod('setAlignment', 'LoadInst', function(x, align, ...) 
#     .Call('R_LoadInst_setAlignment', x, as.integer(align)))
#setMethod('setAlignment', 'StoreInst', function(x, align, ...) 
#     .Call('R_StoreInst_setAlignment', x, as.integer(align)))
setMethod('setOrdering', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_setOrdering', x))
setMethod('setOrdering', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_setOrdering', x))
setMethod('setSyncScopeID', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_setSyncScopeID', x))
setMethod('setSyncScopeID', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_setSyncScopeID', x))
setMethod('setVolatile', 'LoadInst', function(x, ...) 
     .Call('R_LoadInst_setVolatile', x))
setMethod('setVolatile', 'StoreInst', function(x, ...) 
     .Call('R_StoreInst_setVolatile', x))
