getRAPIRoutineSignatures = function()
 list(

'R_CHAR' = list(returnType = StringType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("const char *", x = "SEXP")),
'Rf_isNull' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isSymbol' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isLogical' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isReal' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isComplex' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isExpression' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isEnvironment' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isString' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'Rf_isObject' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", s = "SEXP")),
'ATTRIB' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'OBJECT' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'MARK' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'TYPEOF' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'NAMED' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'REFCNT' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'SET_ATTRIB' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'DUPLICATE_ATTRIB' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", to = "SEXP", from = "SEXP")),
'SHALLOW_DUPLICATE_ATTRIB' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", to = "SEXP", from = "SEXP")),
'MARK_NOT_MUTABLE' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP")),
'IS_S4_OBJECT' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'LENGTH' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'XLENGTH' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_xlen_t", x = "SEXP")),
'TRUELENGTH' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_xlen_t", x = "SEXP")),
'IS_LONG_VEC' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'LEVELS' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'LOGICAL' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("int *", x = "SEXP")),
'INTEGER' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("int *", x = "SEXP")),
'RAW' = list(returnType = pointerType(Int8Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("Rbyte *", x = "SEXP")),
'REAL' = list(returnType = pointerType(DoubleType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("double *", x = "SEXP")),
'COMPLEX' = list(returnType = pointerType(Int64Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("Rcomplex *", x = "SEXP")),
'LOGICAL_RO' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const int *", x = "SEXP")),
'INTEGER_RO' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const int *", x = "SEXP")),
'RAW_RO' = list(returnType = pointerType(Int8Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const Rbyte *", x = "SEXP")),
'REAL_RO' = list(returnType = pointerType(DoubleType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const double *", x = "SEXP")),
'COMPLEX_RO' = list(returnType = pointerType(Int64Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const Rcomplex *", x = "SEXP")),
'VECTOR_ELT' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("SEXP", x = "SEXP", i = "R_xlen_t")),
'SET_STRING_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "SEXP")),
'SET_VECTOR_ELT' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", i = "R_xlen_t", v = "SEXP")),
'STRING_PTR' = list(returnType = pointerType(SEXPType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("SEXP *", x = "SEXP")),
'STRING_PTR_RO' = list(returnType = pointerType(SEXPType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const SEXP *", x = "SEXP")),
'VECTOR_PTR' = list(returnType = pointerType(SEXPType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("SEXP *", x = "SEXP")),
'INTEGER_GET_REGION' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, R_xlen_t = Int64Type, "int *" = pointerType(Int32Type)), cparameterTypes = c("R_xlen_t", sx = "SEXP", i = "R_xlen_t", n = "R_xlen_t", buf = "int *")),
'REAL_GET_REGION' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, R_xlen_t = Int64Type, "double *" = pointerType(DoubleType)), cparameterTypes = c("R_xlen_t", sx = "SEXP", i = "R_xlen_t", n = "R_xlen_t", buf = "double *")),
'LOGICAL_GET_REGION' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, R_xlen_t = Int64Type, "int *" = pointerType(Int32Type)), cparameterTypes = c("R_xlen_t", sx = "SEXP", i = "R_xlen_t", n = "R_xlen_t", buf = "int *")),
'COMPLEX_GET_REGION' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, R_xlen_t = Int64Type, "Rcomplex *" = pointerType(Int64Type)), cparameterTypes = c("R_xlen_t", sx = "SEXP", i = "R_xlen_t", n = "R_xlen_t", buf = "Rcomplex *")),
'RAW_GET_REGION' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, R_xlen_t = Int64Type, "Rbyte *" = pointerType(Int8Type)), cparameterTypes = c("R_xlen_t", sx = "SEXP", i = "R_xlen_t", n = "R_xlen_t", buf = "Rbyte *")),
'INTEGER_IS_SORTED' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'INTEGER_NO_NA' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'REAL_IS_SORTED' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'REAL_NO_NA' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'LOGICAL_IS_SORTED' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'LOGICAL_NO_NA' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'STRING_IS_SORTED' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'STRING_NO_NA' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'TAG' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CAAR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CDAR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CADR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CDDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CDDDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CADDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CADDDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CAD4R' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'CAD5R' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'MISSING' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'SET_TAG' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", y = "SEXP")),
'SETCAR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", y = "SEXP")),
'SETCDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", y = "SEXP")),
'SETCADR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", y = "SEXP")),
'SETCADDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", y = "SEXP")),
'SETCADDDR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP", y = "SEXP")),
'SETCAD4R' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP", y = "SEXP")),
'FORMALS' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'BODY' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'CLOENV' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'RDEBUG' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'RSTEP' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'RTRACE' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'SET_RDEBUG' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_RSTEP' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_RTRACE' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_FORMALS' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_BODY' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_CLOENV' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'PRINTNAME' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'SYMVALUE' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'INTERNAL' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'DDVAL' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'FRAME' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'ENCLOS' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'HASHTAB' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'ENVFLAGS' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'PRCODE' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'PRENV' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'PRVALUE' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'PRSEEN' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'EXTPTR_PROT' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'EXTPTR_TAG' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'EXTPTR_PTR' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = structure(c("void *", "SEXP"), names = c("", ""))),
'R_GetCurrentSrcref' = list(returnType = SEXPType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("SEXP", "int"), names = c("", ""))),
'R_GetSrcFilename' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_asChar' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_coerceVector' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXPTYPE = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "SEXPTYPE"), names = c("", "", ""))),
'Rf_PairToVectorList' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'Rf_VectorToPairList' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'Rf_asCharacterFactor' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'Rf_asLogical' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'Rf_asInteger' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'Rf_asReal' = list(returnType = DoubleType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("double", x = "SEXP")),
'Rf_asComplex' = list(returnType = NA, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rcomplex", x = "SEXP")),
'Rf_acopy_string' = list(returnType = StringType, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("char *", "const char *"), names = c("", ""))),
'Rf_alloc3DArray' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, int = Int32Type, int = Int32Type, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "int", "int", "int"), names = c("", "", "", "", ""))),
'Rf_allocArray' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "SEXP"), names = c("", "", ""))),
'Rf_allocMatrix' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, int = Int32Type, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "int", "int"), names = c("", "", "", ""))),
'Rf_allocList' = list(returnType = SEXPType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("SEXP", "int"), names = c("", ""))),
'Rf_allocS4Object' = list(returnType = SEXPType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "SEXP"),
'Rf_allocSExp' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE"), names = c("", ""))),
'Rf_allocVector3' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, R_xlen_t = Int64Type, "R_allocator_t *" = pointerType(VoidType)), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "R_xlen_t", "R_allocator_t *"), names = c("", "", "", ""))),
'Rf_any_duplicated' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = c("R_xlen_t", x = "SEXP", from_last = "Rboolean")),
'Rf_any_duplicated3' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = c("R_xlen_t", x = "SEXP", incomp = "SEXP", from_last = "Rboolean")),
'Rf_applyClosure' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", "", ""))),
'Rf_classgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_cons' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_copyMatrix' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("void", "SEXP", "SEXP", "Rboolean"), names = c("", "", "", ""))),
'Rf_copyListMatrix' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("void", "SEXP", "SEXP", "Rboolean"), names = c("", "", "", ""))),
'Rf_copyMostAttrib' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_copyVector' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_defineVar' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_dimgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_dimnamesgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_duplicate' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_shallow_duplicate' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'R_duplicate_attr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'R_shallow_duplicate_attr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_lazy_duplicate' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_duplicated' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("SEXP", "SEXP", "Rboolean"), names = c("", "", ""))),
'Rf_eval' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_findFun' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_findVar' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_findVarInFrame' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_findVarInFrame3' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "Rboolean"), names = c("", "", "", ""))),
'R_existsVarInFrame' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP", "SEXP"), names = c("", "", ""))),
'R_removeVarFromFrame' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_getAttrib' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_GetArrayDimnames' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_GetColNames' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_GetMatrixDimnames' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "SEXP *" = pointerType(SEXPType), "SEXP *" = pointerType(SEXPType), "const char **" = NA, "const char **" = NA), cparameterTypes = structure(c("void", "SEXP", "SEXP *", "SEXP *", "const char **", "const char **"), names = c("", "", "", "", "", ""))),
'Rf_GetOption' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_GetOption1' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_GetOptionDigits' = list(returnType = Int32Type, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "int"),
'Rf_GetOptionWidth' = list(returnType = Int32Type, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "int"),
'Rf_GetRowNames' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_gsetVar' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_install' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("SEXP", "const char *"), names = c("", ""))),
'Rf_installChar' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_installNoTrChar' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_installTrChar' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_isOrdered' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isUnordered' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isUnsorted' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("Rboolean", "SEXP", "Rboolean"), names = c("", "", ""))),
'Rf_lengthgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, R_len_t = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "R_len_t"), names = c("", "", ""))),
'Rf_xlengthgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = structure(c("SEXP", "SEXP", "R_xlen_t"), names = c("", "", ""))),
'R_lsInternal' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = structure(c("SEXP", "SEXP", "Rboolean"), names = c("", "", ""))),
'R_lsInternal3' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type, Rboolean = Int1Type), cparameterTypes = structure(c("SEXP", "SEXP", "Rboolean", "Rboolean"), names = c("", "", "", ""))),
'Rf_match' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "int"), names = c("", "", "", ""))),
'Rf_namesgets' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_mkChar' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("SEXP", "const char *"), names = c("", ""))),
'Rf_mkCharLen' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType, int = Int32Type), cparameterTypes = structure(c("SEXP", "const char *", "int"), names = c("", "", ""))),
'Rf_NonNullStringMatch' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_ncols' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("int", "SEXP"), names = c("", ""))),
'Rf_nrows' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("int", "SEXP"), names = c("", ""))),
'Rf_nthcdr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "int"), names = c("", "", ""))),
'R_nchar' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, nchar_type = Int32Type, Rboolean = Int1Type, Rboolean = Int1Type, "const char *" = StringType), cparameterTypes = c("int", string = "SEXP", type_ = "nchar_type", allowNA = "Rboolean", keepNA = "Rboolean", msg_name = "const char *")),
'R_ParseEvalString' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "const char *", "SEXP"), names = c("", "", ""))),
'Rf_PrintValue' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP"), names = c("", ""))),
'Rf_setAttrib' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_setVar' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_str2type' = list(returnType = Int32Type, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("SEXPTYPE", "const char *"), names = c("", ""))),
'Rf_StringBlank' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_substitute' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_topenv' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_translateChar' = list(returnType = StringType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("const char *", "SEXP"), names = c("", ""))),
'Rf_translateCharUTF8' = list(returnType = StringType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("const char *", "SEXP"), names = c("", ""))),
'Rf_type2char' = list(returnType = StringType, parameterTypes = list(SEXPTYPE = Int32Type), cparameterTypes = structure(c("const char *", "SEXPTYPE"), names = c("", ""))),
'Rf_type2rstr' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE"), names = c("", ""))),
'Rf_type2str' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE"), names = c("", ""))),
'Rf_type2str_nowarn' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE"), names = c("", ""))),
'Rf_unprotect_ptr' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP"), names = c("", ""))),
'R_tryEval' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, "int *" = pointerType(Int32Type)), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "int *"), names = c("", "", "", ""))),
'R_tryEvalSilent' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, "int *" = pointerType(Int32Type)), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "int *"), names = c("", "", "", ""))),
'R_GetCurrentEnv' = list(returnType = SEXPType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "SEXP"),
'Rf_isS4' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_asS4' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "Rboolean", "int"), names = c("", "", "", ""))),
'Rf_S3Class' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_isBasicClass' = list(returnType = Int32Type, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("int", "const char *"), names = c("", ""))),
'Rf_getCharCE' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("cetype_t", "SEXP"), names = c("", ""))),
'Rf_mkCharCE' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType, cetype_t = Int32Type), cparameterTypes = structure(c("SEXP", "const char *", "cetype_t"), names = c("", "", ""))),
'Rf_mkCharLenCE' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType, int = Int32Type, cetype_t = Int32Type), cparameterTypes = structure(c("SEXP", "const char *", "int", "cetype_t"), names = c("", "", "", ""))),
'Rf_reEnc' = list(returnType = StringType, parameterTypes = list("const char *" = StringType, cetype_t = Int32Type, cetype_t = Int32Type, int = Int32Type), cparameterTypes = c("const char *", x = "const char *", ce_in = "cetype_t", ce_out = "cetype_t", subst = "int")),
'Rf_reEnc3' = list(returnType = StringType, parameterTypes = list("const char *" = StringType, "const char *" = StringType, "const char *" = StringType, int = Int32Type), cparameterTypes = c("const char *", x = "const char *", fromcode = "const char *", tocode = "const char *", subst = "int")),
'R_forceAndCall' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, int = Int32Type, SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP", n = "int", rho = "SEXP")),
'R_MakeExternalPtr' = list(returnType = SEXPType, parameterTypes = list("void *" = pointerType(VoidType), SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", p = "void *", tag = "SEXP", prot = "SEXP")),
'R_ExternalPtrAddr' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("void *", s = "SEXP")),
'R_ExternalPtrTag' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", s = "SEXP")),
'R_ExternalPtrProtected' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", s = "SEXP")),
'R_ClearExternalPtr' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", s = "SEXP")),
'R_SetExternalPtrAddr' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "void *" = pointerType(VoidType)), cparameterTypes = c("void", s = "SEXP", p = "void *")),
'R_SetExternalPtrTag' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", s = "SEXP", tag = "SEXP")),
'R_SetExternalPtrProtected' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", s = "SEXP", p = "SEXP")),
'R_MakeExternalPtrFn' = list(returnType = SEXPType, parameterTypes = list(DL_FUNC = pointerType(VoidType), SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", p = "DL_FUNC", tag = "SEXP", prot = "SEXP")),
'R_ExternalPtrAddrFn' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("DL_FUNC", s = "SEXP")),
'R_RegisterFinalizer' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", s = "SEXP", fun = "SEXP")),
'R_RegisterCFinalizer' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_CFinalizer_t = pointerType(VoidType)), cparameterTypes = c("void", s = "SEXP", fun = "R_CFinalizer_t")),
'R_RegisterFinalizerEx' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = c("void", s = "SEXP", fun = "SEXP", onexit = "Rboolean")),
'R_RegisterCFinalizerEx' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_CFinalizer_t = pointerType(VoidType), Rboolean = Int1Type), cparameterTypes = c("void", s = "SEXP", fun = "R_CFinalizer_t", onexit = "Rboolean")),
'R_RunPendingFinalizers' = list(returnType = VoidType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "void"),
'R_MakeWeakRef' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = c("SEXP", key = "SEXP", val = "SEXP", fin = "SEXP", onexit = "Rboolean")),
'R_MakeWeakRefC' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, R_CFinalizer_t = pointerType(VoidType), Rboolean = Int1Type), cparameterTypes = c("SEXP", key = "SEXP", val = "SEXP", fin = "R_CFinalizer_t", onexit = "Rboolean")),
'R_WeakRefKey' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", w = "SEXP")),
'R_WeakRefValue' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", w = "SEXP")),
'R_RunWeakRefFinalizer' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", w = "SEXP")),
'R_PromiseExpr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'R_ClosureExpr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'R_BytecodeExpr' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'R_ToplevelExec' = list(returnType = Int1Type, parameterTypes = list("void (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = c("Rboolean", fun = "void (*)(void *)", data = "void *")),
'R_ExecWithCleanup' = list(returnType = SEXPType, parameterTypes = list("SEXP (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), "void (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = c("SEXP", fun = "SEXP (*)(void *)", data = "void *", cleanfun = "void (*)(void *)", cleandata = "void *")),
'R_tryCatch' = list(returnType = SEXPType, parameterTypes = list("SEXP (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), SEXP = SEXPType, "SEXP (*)(SEXP, void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), "void (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = structure(c("SEXP", "SEXP (*)(void *)", "void *", "SEXP", "SEXP (*)(SEXP, void *)", "void *", "void (*)(void *)", "void *"), names = c("", "", "", "", "", "", "", ""))),
'R_tryCatchError' = list(returnType = SEXPType, parameterTypes = list("SEXP (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), "SEXP (*)(SEXP, void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = structure(c("SEXP", "SEXP (*)(void *)", "void *", "SEXP (*)(SEXP, void *)", "void *"), names = c("", "", "", "", ""))),
'R_withCallingErrorHandler' = list(returnType = SEXPType, parameterTypes = list("SEXP (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), "SEXP (*)(SEXP, void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = structure(c("SEXP", "SEXP (*)(void *)", "void *", "SEXP (*)(SEXP, void *)", "void *"), names = c("", "", "", "", ""))),
'R_MakeUnwindCont' = list(returnType = SEXPType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "SEXP"),
'R_ContinueUnwind' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", cont = "SEXP")),
'R_UnwindProtect' = list(returnType = SEXPType, parameterTypes = list("SEXP (*)(void *)" = pointerType(VoidType), "void *" = pointerType(VoidType), "void (*)(void *, Rboolean)" = pointerType(VoidType), "void *" = pointerType(VoidType), SEXP = SEXPType), cparameterTypes = c("SEXP", fun = "SEXP (*)(void *)", data = "void *", cleanfun = "void (*)(void *, Rboolean)", cleandata = "void *", cont = "SEXP")),
'R_NewEnv' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, int = Int32Type, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "int", "int"), names = c("", "", "", ""))),
'R_IsPackageEnv' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", rho = "SEXP")),
'R_PackageEnvName' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", rho = "SEXP")),
'R_FindPackageEnv' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", info = "SEXP")),
'R_IsNamespaceEnv' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", rho = "SEXP")),
'R_NamespaceEnvSpec' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", rho = "SEXP")),
'R_FindNamespace' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", info = "SEXP")),
'R_LockEnvironment' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, Rboolean = Int1Type), cparameterTypes = c("void", env = "SEXP", bindings = "Rboolean")),
'R_EnvironmentIsLocked' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", env = "SEXP")),
'R_LockBinding' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", sym = "SEXP", env = "SEXP")),
'R_unLockBinding' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", sym = "SEXP", env = "SEXP")),
'R_MakeActiveBinding' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", sym = "SEXP", fun = "SEXP", env = "SEXP")),
'R_BindingIsLocked' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("Rboolean", sym = "SEXP", env = "SEXP")),
'R_BindingIsActive' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("Rboolean", sym = "SEXP", env = "SEXP")),
'R_ActiveBindingFunction' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", sym = "SEXP", env = "SEXP")),
'R_HasFancyBindings' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("Rboolean", rho = "SEXP")),
'Rf_errorcall' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType), cparameterTypes = structure(c("void", "SEXP", "const char *"), names = c("", "", ""))),
'Rf_warningcall' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType), cparameterTypes = structure(c("void", "SEXP", "const char *"), names = c("", "", ""))),
'Rf_warningcall_immediate' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType), cparameterTypes = structure(c("void", "SEXP", "const char *"), names = c("", "", ""))),
'R_XDREncodeDouble' = list(returnType = VoidType, parameterTypes = list(double = DoubleType, "void *" = pointerType(VoidType)), cparameterTypes = c("void", d = "double", buf = "void *")),
'R_XDRDecodeDouble' = list(returnType = DoubleType, parameterTypes = list("void *" = pointerType(VoidType)), cparameterTypes = c("double", buf = "void *")),
'R_XDREncodeInteger' = list(returnType = VoidType, parameterTypes = list(int = Int32Type, "void *" = pointerType(VoidType)), cparameterTypes = c("void", i = "int", buf = "void *")),
'R_XDRDecodeInteger' = list(returnType = Int32Type, parameterTypes = list("void *" = pointerType(VoidType)), cparameterTypes = c("int", buf = "void *")),
'R_InitInPStream' = list(returnType = VoidType, parameterTypes = list(R_inpstream_t = pointerType(VoidType), R_pstream_data_t = pointerType(VoidType), R_pstream_format_t = Int32Type, "int (*)(R_inpstream_t)" = pointerType(VoidType), "void (*)(R_inpstream_t, void *, int)" = pointerType(VoidType), "SEXP (*)(SEXP, SEXP)" = pointerType(VoidType), SEXP = SEXPType), cparameterTypes = c("void", stream = "R_inpstream_t", data = "R_pstream_data_t", type = "R_pstream_format_t", inchar = "int (*)(R_inpstream_t)", inbytes = "void (*)(R_inpstream_t, void *, int)", phook = "SEXP (*)(SEXP, SEXP)", pdata = "SEXP")),
'R_InitOutPStream' = list(returnType = VoidType, parameterTypes = list(R_outpstream_t = pointerType(VoidType), R_pstream_data_t = pointerType(VoidType), R_pstream_format_t = Int32Type, int = Int32Type, "void (*)(R_outpstream_t, int)" = pointerType(VoidType), "void (*)(R_outpstream_t, void *, int)" = pointerType(VoidType), "SEXP (*)(SEXP, SEXP)" = pointerType(VoidType), SEXP = SEXPType), cparameterTypes = c("void", stream = "R_outpstream_t", data = "R_pstream_data_t", type = "R_pstream_format_t", version = "int", outchar = "void (*)(R_outpstream_t, int)", outbytes = "void (*)(R_outpstream_t, void *, int)", phook = "SEXP (*)(SEXP, SEXP)", pdata = "SEXP")),
'R_InitFileInPStream' = list(returnType = VoidType, parameterTypes = list(R_inpstream_t = pointerType(VoidType), "int *" = pointerType(Int32Type), R_pstream_format_t = Int32Type, "SEXP (*)(SEXP, SEXP)" = pointerType(VoidType), SEXP = SEXPType), cparameterTypes = c("void", stream = "R_inpstream_t", fp = "int *", type = "R_pstream_format_t", phook = "SEXP (*)(SEXP, SEXP)", pdata = "SEXP")),
'R_InitFileOutPStream' = list(returnType = VoidType, parameterTypes = list(R_outpstream_t = pointerType(VoidType), "int *" = pointerType(Int32Type), R_pstream_format_t = Int32Type, int = Int32Type, "SEXP (*)(SEXP, SEXP)" = pointerType(VoidType), SEXP = SEXPType), cparameterTypes = c("void", stream = "R_outpstream_t", fp = "int *", type = "R_pstream_format_t", version = "int", phook = "SEXP (*)(SEXP, SEXP)", pdata = "SEXP")),
'R_Serialize' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_outpstream_t = pointerType(VoidType)), cparameterTypes = c("void", s = "SEXP", ops = "R_outpstream_t")),
'R_Unserialize' = list(returnType = SEXPType, parameterTypes = list(R_inpstream_t = pointerType(VoidType)), cparameterTypes = c("SEXP", ips = "R_inpstream_t")),
'R_SerializeInfo' = list(returnType = SEXPType, parameterTypes = list(R_inpstream_t = pointerType(VoidType)), cparameterTypes = c("SEXP", ips = "R_inpstream_t")),
'R_do_slot' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", obj = "SEXP", name = "SEXP")),
'R_do_slot_assign' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", obj = "SEXP", name = "SEXP", value = "SEXP")),
'R_has_slot' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("int", obj = "SEXP", name = "SEXP")),
'R_S4_extends' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", klass = "SEXP", useTable = "SEXP")),
'R_do_MAKE_CLASS' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType), cparameterTypes = c("SEXP", what = "const char *")),
'R_getClassDef' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType), cparameterTypes = c("SEXP", what = "const char *")),
'R_getClassDef_R' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", what = "SEXP")),
'R_has_methods_attached' = list(returnType = Int1Type, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "Rboolean"),
'R_isVirtualClass' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("Rboolean", class_def = "SEXP", env = "SEXP")),
'R_extends' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("Rboolean", class1 = "SEXP", class2 = "SEXP", env = "SEXP")),
'R_do_new_object' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", class_def = "SEXP")),
'R_check_class_and_super' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, "const char **" = NA, SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP", valid = "const char **", rho = "SEXP")),
'R_check_class_etc' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, "const char **" = NA), cparameterTypes = c("int", x = "SEXP", valid = "const char **")),
'R_PreserveObject' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP"), names = c("", ""))),
'R_ReleaseObject' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("void", "SEXP"), names = c("", ""))),
'R_NewPreciousMSet' = list(returnType = SEXPType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("SEXP", "int"), names = c("", ""))),
'R_PreserveInMSet' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", mset = "SEXP")),
'R_ReleaseFromMSet' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", mset = "SEXP")),
'R_ReleaseMSet' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", mset = "SEXP", keepSize = "int")),
'R_dot_Last' = list(returnType = VoidType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "void"),
'R_RunExitFinalizers' = list(returnType = VoidType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "void"),
'R_system' = list(returnType = Int32Type, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("int", "const char *"), names = c("", ""))),
'R_compute_identical' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, int = Int32Type), cparameterTypes = structure(c("Rboolean", "SEXP", "SEXP", "int"), names = c("", "", "", ""))),
'R_body_no_src' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'R_orderVector' = list(returnType = VoidType, parameterTypes = list("int *" = pointerType(Int32Type), int = Int32Type, SEXP = SEXPType, Rboolean = Int1Type, Rboolean = Int1Type), cparameterTypes = c("void", indx = "int *", n = "int", arglist = "SEXP", nalast = "Rboolean", decreasing = "Rboolean")),
'R_orderVector1' = list(returnType = VoidType, parameterTypes = list("int *" = pointerType(Int32Type), int = Int32Type, SEXP = SEXPType, Rboolean = Int1Type, Rboolean = Int1Type), cparameterTypes = c("void", indx = "int *", n = "int", x = "SEXP", nalast = "Rboolean", decreasing = "Rboolean")),
'Rf_allocVector' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, R_xlen_t = Int64Type), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "R_xlen_t"), names = c("", "", ""))),
'Rf_conformable' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_elt' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = structure(c("SEXP", "SEXP", "int"), names = c("", "", ""))),
'Rf_inherits' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType), cparameterTypes = structure(c("Rboolean", "SEXP", "const char *"), names = c("", "", ""))),
'Rf_isArray' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isFactor' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isFrame' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isFunction' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isInteger' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isLanguage' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isList' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isMatrix' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isNewList' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isNumber' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isNumeric' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isPairList' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isPrimitive' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isTs' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isUserBinop' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isValidString' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isValidStringF' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isVector' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isVectorAtomic' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isVectorList' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_isVectorizable' = list(returnType = Int1Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("Rboolean", "SEXP"), names = c("", ""))),
'Rf_lang1' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_lang2' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_lang3' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_lang4' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", ""))),
'Rf_lang5' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", "", ""))),
'Rf_lang6' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", "", "", ""))),
'Rf_lastElt' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_lcons' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_length' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("R_len_t", "SEXP"), names = c("", ""))),
'Rf_list1' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_list2' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_list3' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", ""))),
'Rf_list4' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", ""))),
'Rf_list5' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", "", ""))),
'Rf_list6' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP", "SEXP"), names = c("", "", "", "", "", "", ""))),
'Rf_listAppend' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP", "SEXP"), names = c("", "", ""))),
'Rf_mkNamed' = list(returnType = SEXPType, parameterTypes = list(SEXPTYPE = Int32Type, "const char **" = NA), cparameterTypes = structure(c("SEXP", "SEXPTYPE", "const char **"), names = c("", "", ""))),
'Rf_mkString' = list(returnType = SEXPType, parameterTypes = list("const char *" = StringType), cparameterTypes = structure(c("SEXP", "const char *"), names = c("", ""))),
'Rf_nlevels' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("int", "SEXP"), names = c("", ""))),
'Rf_stringPositionTr' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType), cparameterTypes = structure(c("int", "SEXP", "const char *"), names = c("", "", ""))),
'Rf_ScalarComplex' = list(returnType = SEXPType, parameterTypes = list(Rcomplex = NA), cparameterTypes = structure(c("SEXP", "Rcomplex"), names = c("", ""))),
'Rf_ScalarInteger' = list(returnType = SEXPType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("SEXP", "int"), names = c("", ""))),
'Rf_ScalarLogical' = list(returnType = SEXPType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("SEXP", "int"), names = c("", ""))),
'Rf_ScalarRaw' = list(returnType = SEXPType, parameterTypes = list(Rbyte = Int8Type), cparameterTypes = structure(c("SEXP", "Rbyte"), names = c("", ""))),
'Rf_ScalarReal' = list(returnType = SEXPType, parameterTypes = list(double = DoubleType), cparameterTypes = structure(c("SEXP", "double"), names = c("", ""))),
'Rf_ScalarString' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_xlength' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("R_xlen_t", "SEXP"), names = c("", ""))),
'XLENGTH' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_xlen_t", x = "SEXP")),
'XTRUELENGTH' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_xlen_t", x = "SEXP")),
'LENGTH_EX' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, "const char *" = StringType, int = Int32Type), cparameterTypes = c("int", x = "SEXP", file = "const char *", line = "int")),
'XLENGTH_EX' = list(returnType = Int64Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_xlen_t", x = "SEXP")),
'Rf_protect' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", ""))),
'Rf_unprotect' = list(returnType = VoidType, parameterTypes = list(int = Int32Type), cparameterTypes = structure(c("void", "int"), names = c("", ""))),
'R_ProtectWithIndex' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, "PROTECT_INDEX *" = pointerType(Int32Type)), cparameterTypes = structure(c("void", "SEXP", "PROTECT_INDEX *"), names = c("", "", ""))),
'R_Reprotect' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, PROTECT_INDEX = Int32Type), cparameterTypes = structure(c("void", "SEXP", "PROTECT_INDEX"), names = c("", "", ""))),
'CAR' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", e = "SEXP")),
'DATAPTR' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("void *", x = "SEXP")),
'DATAPTR_RO' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const void *", x = "SEXP")),
'DATAPTR_OR_NULL' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const void *", x = "SEXP")),
'LOGICAL_OR_NULL' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const int *", x = "SEXP")),
'INTEGER_OR_NULL' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const int *", x = "SEXP")),
'REAL_OR_NULL' = list(returnType = pointerType(DoubleType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const double *", x = "SEXP")),
'COMPLEX_OR_NULL' = list(returnType = pointerType(Int64Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const Rcomplex *", x = "SEXP")),
'RAW_OR_NULL' = list(returnType = pointerType(Int8Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("const Rbyte *", x = "SEXP")),
'INTEGER_ELT' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("int", x = "SEXP", i = "R_xlen_t")),
'REAL_ELT' = list(returnType = DoubleType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("double", x = "SEXP", i = "R_xlen_t")),
'LOGICAL_ELT' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("int", x = "SEXP", i = "R_xlen_t")),
'COMPLEX_ELT' = list(returnType = NA, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("Rcomplex", x = "SEXP", i = "R_xlen_t")),
'RAW_ELT' = list(returnType = Int8Type, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("Rbyte", x = "SEXP", i = "R_xlen_t")),
'STRING_ELT' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("SEXP", x = "SEXP", i = "R_xlen_t")),
'SET_LOGICAL_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, int = Int32Type), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "int")),
'SET_INTEGER_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, int = Int32Type), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "int")),
'SET_REAL_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, double = DoubleType), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "double")),
'SET_COMPLEX_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, Rcomplex = NA), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "Rcomplex")),
'SET_RAW_ELT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type, Rbyte = Int8Type), cparameterTypes = c("void", x = "SEXP", i = "R_xlen_t", v = "Rbyte")),
'ALTREP_CLASS' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'R_altrep_data1' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'R_altrep_data2' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("SEXP", x = "SEXP")),
'R_set_altrep_data1' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'R_set_altrep_data2' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'LOGICAL0' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("int *", x = "SEXP")),
'INTEGER0' = list(returnType = pointerType(Int32Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("int *", x = "SEXP")),
'REAL0' = list(returnType = pointerType(DoubleType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("double *", x = "SEXP")),
'COMPLEX0' = list(returnType = pointerType(Int64Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("Rcomplex *", x = "SEXP")),
'RAW0' = list(returnType = pointerType(Int8Type), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("Rbyte *", x = "SEXP")),
'ALTREP' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'R_asHashtable' = list(returnType = NA, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("R_hashtab_type", h = "SEXP")),
'R_HashtabSEXP' = list(returnType = SEXPType, parameterTypes = list(R_hashtab_type = NA), cparameterTypes = c("SEXP", h = "R_hashtab_type")),
'R_isHashtable' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", h = "SEXP")),
'R_mkhashtab' = list(returnType = NA, parameterTypes = list(int = Int32Type, int = Int32Type), cparameterTypes = c("R_hashtab_type", type = "int", "int")),
'R_gethash' = list(returnType = SEXPType, parameterTypes = list(R_hashtab_type = NA, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", h = "R_hashtab_type", key = "SEXP", nomatch = "SEXP")),
'R_sethash' = list(returnType = SEXPType, parameterTypes = list(R_hashtab_type = NA, SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("SEXP", h = "R_hashtab_type", key = "SEXP", value = "SEXP")),
'R_remhash' = list(returnType = Int32Type, parameterTypes = list(R_hashtab_type = NA, SEXP = SEXPType), cparameterTypes = c("int", h = "R_hashtab_type", key = "SEXP")),
'R_numhash' = list(returnType = Int32Type, parameterTypes = list(R_hashtab_type = NA), cparameterTypes = c("int", h = "R_hashtab_type")),
'R_typhash' = list(returnType = Int32Type, parameterTypes = list(R_hashtab_type = NA), cparameterTypes = c("int", h = "R_hashtab_type")),
'R_maphash' = list(returnType = SEXPType, parameterTypes = list(R_hashtab_type = NA, SEXP = SEXPType), cparameterTypes = c("SEXP", h = "R_hashtab_type", FUN = "SEXP")),
'R_maphashC' = list(returnType = VoidType, parameterTypes = list(R_hashtab_type = NA, "void (*)(SEXP, SEXP, void *)" = pointerType(VoidType), "void *" = pointerType(VoidType)), cparameterTypes = c("void", h = "R_hashtab_type", FUN = "void (*)(SEXP, SEXP, void *)", data = "void *")),
'R_clrhash' = list(returnType = VoidType, parameterTypes = list(R_hashtab_type = NA), cparameterTypes = c("void", h = "R_hashtab_type")),
'SET_TYPEOF' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_OBJECT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_S4_OBJECT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP")),
'UNSET_S4_OBJECT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP")),
'R_curErrorBuf' = list(returnType = StringType, parameterTypes = structure(list(), names = character(0)), cparameterTypes = "const char *"),
'IS_SCALAR' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("int", x = "SEXP", type = "int")),
'Rf_psmatch' = list(returnType = Int1Type, parameterTypes = list("const char *" = StringType, "const char *" = StringType, Rboolean = Int1Type), cparameterTypes = structure(c("Rboolean", "const char *", "const char *", "Rboolean"), names = c("", "", "", ""))),
'SETLENGTH' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("void", x = "SEXP", v = "R_xlen_t")),
'SET_TRUELENGTH' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, R_xlen_t = Int64Type), cparameterTypes = c("void", x = "SEXP", v = "R_xlen_t")),
'SETLEVELS' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("int", x = "SEXP", v = "int")),
'SET_ENVFLAGS' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'SET_FRAME' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_ENCLOS' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_HASHTAB' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_PRENV' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_PRVALUE' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'SET_PRCODE' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP", v = "SEXP")),
'STDVEC_DATAPTR' = list(returnType = pointerType(VoidType), parameterTypes = list( SEXP = SEXPType), cparameterTypes = c("void *", x = "SEXP")),
'IS_GROWABLE' = list(returnType = Int32Type, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("int", x = "SEXP")),
'SET_GROWABLE_BIT' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = c("void", x = "SEXP")),
'SET_NAMED' = list(returnType = VoidType, parameterTypes = list(SEXP = SEXPType, int = Int32Type), cparameterTypes = c("void", x = "SEXP", v = "int")),
'R_tryWrap' = list(returnType = SEXPType, parameterTypes = list(SEXP = SEXPType), cparameterTypes = structure(c("SEXP", "SEXP"), names = c("", "")))

)
